- name: Include OS specifix install task
  include: "install.{{ os_family }}.yml"

- name: Install Hex and Rebar
  command: "mix {{ item.name }} --force"
  args:
    creates: "~/.mix/{{ item.file }}"
  with_items:
    - name: "local.hex"
      file: "archives/hex.ez"
    - name: "local.rebar"
      file: "rebar"

- name: Checkout Elixir package
  git:
    repo: "https://github.com/rrrene/credo"
    dest: "~/.elixir/packages/credo"
    version: "v0.9.2"
    force: yes
    update: no
  register: credo_repo

- name: Install Elixir package
  command: mix deps.get && mix archive.build && mix archive.install
  args:
    chdir: ~/.elixir/packages/credo
  when: credo_repo.changed

