- name: install Java
  homebrew_cask:
    name: oracle-jdk
    state: present
  when:
    - ansible_os_family == 'Darwin'

- name: detect Java home path
  shell: $SHELL -lc "java -XshowSettings:properties -version 2>&1 > /dev/null | grep -e 'java.home' | sed -e 's/^[[:space:]]*java.home[[:space:]]*=[[:space:]]*//'"
  register: java_home

- debug:
    var: java_home

- name: Clean list of disabled algorithm
  become: true
  replace:
    path: "{{ java_home.stdout }}/conf/security/java.security"
    regexp: "^{{ item }}=(?:\\s*[^\\\\\\n]*?, \\\\$)*(?:\\s*[^\\\\\\\n]*?$)"
    replace: "{{ item }}="
  with_items:
    - jdk.certpath.disabledAlgorithms
    - jdk.jar.disabledAlgorithms
    - jdk.tls.disabledAlgorithms
  when:
    - ansible_os_family == 'Darwin'

- name: Disable some policy
  become: true
  replace:
    path: "{{ java_home.stdout }}/conf/security/java.security"
    regexp: 'policy.ignoreIdentityScope=false'
    replace: 'policy.ignoreIdentityScope=true'
  when:
    - ansible_os_family == 'Darwin'
