---
sudo: required
language: objective-c
os: osx

before_install:

jobs:
  include:
    - script: ./bootstrap.sh
    - script: pip install ansible && ansible-playbook -i "localhost," -D -c local playbook.yml --syntax-check
    - script: pip install ansible-lint && ansible-lint playbook.yml
