---
sudo: required
language: objective-c
# 10.11 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode7.3

before_install:
  # Uninstall existing brew installation.
  - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"'
  - rm -rf /usr/local/Homebrew
  - rm -rf /usr/local/Caskroom
  - rm -rf /usr/local/bin/brew

script:
  # Test the playbook.
  - "travis_wait 30 ./bootstrap.sh"
