---
sudo: required
language: objective-c
# 10.11 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
os: osx
osx_image: xcode9.2

before_install:
  # Uninstall existing brew installation.
  # - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- -f'

script:
  # Test the playbook.
  - ./bootstrap.sh
