---
sudo: required
jobs:
  include:
    - stage: playbook spec
      os: osx
      script: ./bootstrap.sh
    - stage: playbook spec
      language: python
      dist: trusty
      python:
        - "3.6"
      install:
        - pip install --upgrade pip
        - pip install ansible
      script: ansible-playbook -i "localhost," -D -c local playbook.yml --syntax-check --connection=local --sudo
    - stage: playbook spec
      language: python
      dist: trusty
      python:
        - "3.6"
      install:
        - pip install --upgrade pip
        - pip install ansible-lint
      script: ansible-lint playbook.yml
