- hosts: 127.0.0.1
  connection: local
  become: false
  vars:
    os_family: "{{ ansible_facts['os_family'] | lower }}"
    rbenv:
      env: system
      version: v1.0.0
      default_ruby: 3.0.2
      rubies:
        - version: 3.0.2
  roles:
    - name: Preapre
      role: prepare
      tags: ['always']

    - role: ruby
      tags: ['langs', 'ruby']

    - role: node
      tags: ['langs', 'node']

    - role: go
      tags: ['langs', 'node']

    - role: nim
      tags: ['langs', 'nim']

    - role: elixir
      tags: ['langs', 'elixir']

    - role: java-sdk
      tags: ['langs', 'java']

    - role: apps
      tags: ['apps']

    - role: vim
      tags: ['apps', 'vim']

    - role: dotfiles
      tags: ['dotfiles']
