---
-
  hosts: all
  sudo: false
  tasks:
  -
    name: Taps homebrew repos
    homebrew_tap: tap={{ item }} state=present
    with_items:
      - thoughtbot/formulae
      - caskroom/cask
      - caskroom/fonts

  -
    name: install brew packages
    homebrew: name={{ item }}  state=latest update_homebrew=yes
    with_items:
      - brew-cask
      - node
      - docker
      - docker-compose
      - xhyve
      - go
      - wget
      - the_silver_searcher
      - jsonpp

  -
    name: Install gems
    gem: name={{ item }} state=latest user_install=no
    sudo: yes
    with_items:
      - haml-lint
      - ruby-lint
      - sqlint
      - rubocop

  -
    name: install npm packages
    npm: name={{ item }} state=present global=yes
    with_items:
      - eslint
      - babel-eslint
      - eslint-plugin-react
      - json-lint
      - bower
      - grunt-cli

  -
    name: install casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - font-fira-mono
      - font-fira-mono-for-powerline
      - virtualbox
      - iterm2
      - slack
      - skype
      - lunchy

  -
    name: install latest VIM
    homebrew: name=vim state=latest update_homebrew=yes install_options=override-system-vi

  -
    name: install vundle
    git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim update=no

  -
    name: touch local.dotfiles
    file: path=~/.{{ item }} state=touch
    with_items:
      - vimrc.bundles.local
      - profile

  -
    name: setup dotfiles
    template: src=dotfiles/{{ item }} dest=~/.{{ item }} force=yes
    with_items:
      - aliases
      - vimrc
      - vimrc.bundles
      - bashrc
      - gitconfig
      - gitignore_global
      - eslintrc

  -
    name: setup ~/.bashrc
    lineinfile: dest=~/.profile line="source ~/.bashrc" regexp="bashrc"

  -
    name: install vim plugins
    shell: "vim +PluginInstall +qal"

  -
    name: setup go path
    file: path="~/.go" state="directory"

  -
    name: load dotfiles
    shell: source ~/.bashrc

  -
    name: get user path
    stat: path="~"
    register: homepath

  -
    name: build docker-machine
    shell: go get github.com/docker/machine && cd ~/.go/src/github.com/docker/machine && make build

  -
    name: install docker-machine
    sudo: true
    shell: cd "{{ homepath.stat.path }}/.go/src/github.com/docker/machine" && make install

  -
    name: build docker-machine-driver-xhyve
    shell: go get -u github.com/zchee/docker-machine-driver-xhyve && cd "{{ homepath.stat.path }}/.go/src/github.com/zchee/docker-machine-driver-xhyve" && make build

  -
    name: install docker-machine-driver-xhyve
    shell: cd "{{ homepath.stat.path }}/.go/src/github.com/zchee/docker-machine-driver-xhyve" && make install

  -
    name: set docker-machive-dirver-xhyve mode
    sudo: true
    file: path="{{ homepath.stat.path }}/.go/bin/docker-machine-driver-xhyve" mode="u+s" owner="root" group="wheel"

  -
    name: create dev machine
    shell: docker-machine create dev --driver xhyve --xhyve-experimental-nfs-share --xhyve-disk-size "50000" --xhyve-cpu-count "2" --xhyve-memory-size "3072"

  -
    name: setup iTerm2
    shell: /usr/libexec/PlistBuddy -c 'Set :"New Bookmarks":0:"{{ item.name }}" "{{ item.value }}"' ~/Library/Preferences/com.googlecode.iterm2.plist
    with_items:
      - { name: 'Normal Font', value: 'Fira Mono 10' }
      - { name: 'Non Ascii Font', value: 'Fira Mono 10' }
      - { name: 'Use Italic Font', value: 'false' }
      - { name: 'Silence Bell', value: 'true' }
      - { name: 'Flashing Bell', value: 'false' }
      - { name: 'BM Growl', value: 'false' }
      - { name: 'Scrollback Lines', value: '15000' }


