---
-
  hosts: all
  sudo: false
  tasks:
  -
    name: Taps homebrew repos
    homebrew_tap: tap={{ item }} state=present
    with_items:
      - thoughtbot/formulae
      - caskroom/cask
      - caskroom/fonts
  -
    name: install brew packages
    homebrew: name={{ item }}  state=latest update_homebrew=yes
    with_items:
      - brew-cask
      - node
  -
    name: Install gems
    gem: name={{ item }} state=latest user_install=no
    sudo: yes
    with_items:
      - haml-lint
      - ruby-lint
      - sqlint
      - rubocop
  -
    name: install npm packages
    npm: name={{ item }} state=present global=yes
    with_items:
      - eslint
      - babel-eslint
      - eslint-plugin-react
      - json-lint
      - bower
      - grunt-cli
  -
    name: install casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - font-fira-mono
      - font-fira-mono-for-powerline
      - iterm2
      - slack
      - skype
  -
    name: install latest VIM
    homebrew: name=vim state=latest update_homebrew=yes install_options=override-system-vi
  -
    name: install vundle
    git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim update=no
  -
    name: touch local.dotfiles
    file: path=~/.{{ item }} state=touch
    with_items:
      - vimrc.bundles.local
  -
    name: setup dotfiles
    template: src=dotfiles/{{ item }} dest=~/.{{ item }} force=yes
    with_items:
      - vimrc
      - vimrc.bundles
      - gitconfig
      - gitignore_global
      - eslintrc
  -
    name: install vim plugins
    shell: "vim +PluginInstall +qal"
  -
    name: install Fira Mono into iTerm2
    shell: /usr/libexec/PlistBuddy -c 'Set :"New Bookmarks":0:"{{ item.name }}" "{{ item.value }}"' ~/Library/Preferences/com.googlecode.iterm2.plist
    with_items:
      - { name: "Normal Font", value: "Fira Mono 10" }
      - { name: "Non Ascii Font", value: "Fira Mono 10" }
