---
-
  hosts: all
  sudo: false
  tasks:
  -
    name: Taps homebrew repos
    homebrew_tap: tap={{ item }} state=present
    with_items:
      - thoughtbot/formulae
      - caskroom/cask
      - caskroom/fonts
  -
    name: install brew packages
    homebrew: name={{ item }}  state=latest update_homebrew=yes
    with_items:
      - brew-cask
      - node
      - docker
      - docker-machine
      - docker-compose
      - boot2docker
      - wget
      - kubernetes-cli
      - the_silver_searcher
      - jsonpp
  -
    name: Install gems
    gem: name={{ item }} state=latest user_install=no
    sudo: yes
    with_items:
      - haml-lint
      - ruby-lint
      - sqlint
      - rubocop
  -
    name: install npm packages
    npm: name={{ item }} state=present global=yes
    with_items:
      - eslint
      - babel-eslint
      - eslint-plugin-react
      - json-lint
      - bower
      - grunt-cli
  -
    name: install casks
    homebrew_cask: name={{ item }} state=present
    with_items:
      - font-fira-mono
      - font-fira-mono-for-powerline
      - virtualbox
      - iterm2
      - slack
      - skype
      - lunchy
  -
    name: install latest VIM
    homebrew: name=vim state=latest update_homebrew=yes install_options=override-system-vi
  -
    name: install vundle
    git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim update=no
  -
    name: touch local.dotfiles
    file: path=~/.{{ item }} state=touch
    with_items:
      - vimrc.bundles.local
  -
    name: setup dotfiles
    template: src=dotfiles/{{ item }} dest=~/.{{ item }} force=yes
    with_items:
      - vimrc
      - vimrc.bundles
      - bashrc
      - gitconfig
      - gitignore_global
      - eslintrc
  -
    name: install vim plugins
    shell: "vim +PluginInstall +qal"
  -
    name: setup boot2docker
    shell: boot2docker init
  -
    name: setup services
    template: src=services/{{ item }}.j2 dest=~/Library/LaunchAgents/{{ item }} force=yes mode=770
    with_items:
      - com.user.boot2docker.plist
  -
    name: Up services
    shell: lunchy start {{ item }}
    with_items:
      - boot2docker
  -
    name: boot2docker DNS setup
    shell: boot2docker ssh "echo 'EXTRA_ARGS=\"--dns 10.40.40.1 --dns 8.8.8.8 --insecure-registry registry.default.kube.ul.home\"' | sudo tee /var/lib/boot2docker/profile"
  -
    name: setup iTerm2
    shell: /usr/libexec/PlistBuddy -c 'Set :"New Bookmarks":0:"{{ item.name }}" "{{ item.value }}"' ~/Library/Preferences/com.googlecode.iterm2.plist
    with_items:
      - { name: 'Normal Font', value: 'Fira Mono 10' }
      - { name: 'Non Ascii Font', value: 'Fira Mono 10' }
      - { name: 'Use Italic Font', value: 'false' }
      - { name: 'Silence Bell', value: 'true' }
      - { name: 'Flashing Bell', value: 'false' }
      - { name: 'BM Growl', value: 'false' }
      - { name: 'Scrollback Lines', value: '15000' }
