- hosts: all
  become: false
  tasks:
    - name: Prepare
      include: tasks/prepare.yml

    - name: Setup apps
      include: tasks/apps.yml
      tags:
        - apps

    - name: Install ruby
      include: tasks/langs/ruby.yml
      tags:
         - langs
         - ruby

    - name: Install node
      include: tasks/langs/node.yml
      tags:
         - langs
         - node

    - name: Install go
      include: tasks/langs/go.yml
      tags:
         - langs
         - go

    - name: Install nim
      include: tasks/langs/nim.yml
      tags:
         - langs
         - nim

    - name: Install elixir
      include: tasks/langs/elixir.yml
      tags:
         - langs
         - elixir

    - name: Install VIM
      include: tasks/vim.yml
      tags:
        - apps
        - vim

    - name: Setup dotfiles
      include: tasks/dotfiles.yml
      tags:
        - dotfiles
