- hosts: all
  vars:
    os_family: "{{ ansible_facts['os_family'] | lower }}"
  roles:
    - name: Preapre
      role: prepare
      tags: ['always']

    - role: apps
      tags: ['apps']

    - role: vim
      tags: ['apps', 'vim']

    - role: dotfiles
      tags: ['dotfiles']

    - role: ruby
      tags: ['langs', 'ruby']

    - role: node
      tags: ['langs', 'node']

    - role: go
      tags: ['langs', 'go']

    - role: nim
      tags: ['langs', 'nim']

    - role: elixir
      tags: ['langs', 'elixir']

