- name: get user path
  stat:
    path: "~"
  register: homepath

- name: touch local.dotfiles
  file:
    path: "~/.{{ item }}"
    state: touch
  with_items:
    - profile

- name: setup dotfiles
  template:
    src: "dotfiles/{{ item }}"
    dest: "~/.{{ item }}"
    force: yes
  with_items:
    - aliases
    - bashrc
    - gitconfig
    - gitignore_global
    - hgrc
    - hgignore
  register: dotfiles

- name: setup ~/.bashrc
  lineinfile:
    dest: ~/.profile
    line: "source ~/.bashrc"
    regexp: "bashrc"

- name: load dotfiles
  command: source ~/.bashrc
  when: dotfiles.changed
