- name: install Java
  homebrew_cask:
    name: java
    state: present

- name: Clean list of disabled algorithm
  become: true
  replace:
    path: '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/security/java.security'
    regexp: "^{{ item }}=(?:\\s*[^\\\\\\n]*?, \\\\$)*(?:\\s*[^\\\\\\\n]*?$)"
    replace: "{{ item }}="
  with_items:
    - jdk.certpath.disabledAlgorithms
    - jdk.jar.disabledAlgorithms
    - jdk.tls.disabledAlgorithms


- name: Disable some policy
  become: true
  replace:
    path: '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/security/java.security'
    regexp: 'policy.ignoreIdentityScope=false'
    replace: 'policy.ignoreIdentityScope=true'
