- name: Update brew
  homebrew:
    update_homebrew: yes

- name: Taps homebrew repos
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - thoughtbot/formulae
    - homebrew/cask
    - homebrew/cask-fonts
    - homebrew/cask-versions
