- name: Update packages
  become: yes
  become_method: sudo
  apt:
    upgrade: dist
    update_cache: yes

- name: Install homebrew wrapper
  apt:
    name:
      - linuxbrew-wrapper
  become: yes
  become_method: sudo

- name: Update brew
  homebrew:
    update_homebrew: yes
  become: yes
  become_method: sudo
