- name: Install brew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - node

- name: Install npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items:
    - eslint
    - livedown
    - babel-eslint
    - babel-preset-stage-0
    - eslint-plugin-react
    - eslint-plugin-flowtype
    - eslint-plugin-import
    - eslint-import-resolver-webpack
    - eslint-plugin-jsx-a11y
    - eslint-config-airbnb
    - eslint-plugin-vue
    - lint-staged
    - json-lint
    - bower
    - grunt-cli
    - stylelint
    - get-graphql-schema

- name: Setup dotfiles
  template:
    src: "dotfiles/{{ item }}"
    dest: "~/.{{ item }}"
    force: yes
  with_items:
    - eslintrc
