- name: Install brew packages
  homebrew:
    name:
      - wget
      - the_silver_searcher
      - tmux
      - jsonpp
      - hub
      - mercurial
      - fzf
      - ipcalc
      - git-flow-avh
      - gpg
      - mas
      - tmux
      - dockutil
    state: present

- name: Install apps from casks
  homebrew_cask:
    name:
      - font-fira-mono
      - font-roboto-mono
      - font-hack
      - font-source-code-pro
      - font-fira-mono-for-powerline
      - font-monoid
      - iterm2
      - slack
      - skype
      - telegram-desktop
      - firefox-beta
      - tunnelblick
      - sourcetree
      - lunchy
      - insomnia
      - spotify
      - docker
      - 1password
      - spotify
      - dash
      - vagrant
      - virtualbox
      - rectangle
      - visual-studio-code
    state: present

- name: Install brew packages
  homebrew:
    name: "{{ brew_apps | join(',') }}"
    state: present

- name: Install apps from casks
  homebrew_cask:
    name: "{{ cask_apps | join(',') }}"
    state: present
      - rectangle
      - visual-studio-code

- name: Setup iTerm
  include: iterm.yml

- name: Cleanup Dock
  command: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items:
    - Siri
    - Launchpad
    - Safari
    - Contacts
    - Notes
    - Reminders
    - Maps
    - Photos
    - Messsages
    - FaceTime
    - Music
    - Podcasts
    - TV
    - Books
    - App Store
