- name: Install brew packages
  homebrew:
    name:
      - wget
      - the_silver_searcher
      - tmux
      - jsonpp
      - hub
      - mercurial
      - fzf
      - ipcalc
      - hadolint
      - git-flow-avh
      - svn
      - gpg
      - mas
      - tmux
      - dockutil
      - lunchy
    state: present

- name: Install apps from casks
  homebrew_cask:
    name:
      - font-fira-mono
      - font-roboto-mono
      - font-hack
      - font-source-code-pro
      - font-fira-mono-for-powerline
      - font-monoid
      - iterm2
      - slack
      - skype
      - telegram-desktop
      - firefox-beta
      - tunnelblick
      - sourcetree
      - insomnia
      - spotify
      - docker
      - 1password
      - spotify
      - dash
      - vagrant
      - virtualbox
      - rectangle
      - visual-studio-code
      - grammarly
      - pock
    state: present

- name: Setup iTerm
  include_tasks: iterm.yml
  ignore_errors: true
  when: False

- name: Cleanup Dock
  command: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items:
    - App Store
    - Books
    - Calendar
    - Contacts
    - FaceTime
    - Keynote
    - Launchpad
    - Maps
    - Messages
    - Music
    - Notes
    - Numbers
    - Pages
    - Photos
    - Podcasts
    - Reminders
    - Safari
    - Siri
    - TV
    - Заметки
    - Календарь
    - Карты
    - Контакты
    - Музыка
    - Напоминания
    - Подкасты
    - Системные настройки
    - Сообщения
    - Фото
