- name: Install brew packages
  homebrew:
    name:
      - wget
      - the_silver_searcher
      - tmux
      - jsonpp
      - hub
      - mercurial
      - fzf
      - ipcalc
      - git-flow-avh
      - gpg
    state: present

- name: Install apps from casks
  homebrew_cask:
    name:
      - font-fira-mono
      - font-roboto-mono
      - font-hack
      - font-source-code-pro
      - font-fira-mono-for-powerline
      - iterm2
      - slack
      - skype
      - telegram-desktop
      - hipchat
      - firefox-beta
      - tunnelblick
      - sourcetree
      - lunchy
      - insomnia
      - spotify
      - docker
      - 1password
      - spotify
      - dash
    state: present
