- name: Install deps
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  become: True

- name: Installing apt-key
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: True

- name: Add deb repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: TrueS

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: True
  changed_when: false

- name: Install
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: True

- name: Add current user to Docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: True

- name: "Ensure Docker is {{ docker.start | ternary('started','stopped') }}"
  service:
    name: docker
    state: "{{ docker.start | ternary('restarted','stopped') }}"
    enabled: "{{ docker.service_enabled }}"
  become: True
