- name: Install common packages
  become: true
  apt:
    name:
      - wget
      - build-essential
      - curl
      - file
      - git
      - silversearcher-ag
      - gpg
      - tmux
      - ipcalc

- name: Install docker
  include_tasks: debian.docker.yml

- name: Install brew packages
  homebrew:
    name:
      - hub
      - fzf
      - git-flow-avh
    state: present
