- name: Check OS specifix deps task exists
  local_action: stat path="{{ role_path }}/tasks/setup.{{ os_family }}.yml"
  register: os_task
  become: no

- name: Include OS specifix setup task
  include: "setup.{{ os_family }}.yml"
  when: os_task.stat.exists

- name: Register brew apps list
  set_fact:
    npm_packages:
      - eslint
      - livedown
      - babel-eslint
      - babel-preset-stage-0
      - eslint-plugin-react
      - eslint-plugin-flowtype
      - eslint-plugin-import
      - eslint-import-resolver-webpack
      - eslint-plugin-jsx-a11y
      - eslint-config-airbnb
      - eslint-plugin-vue
      - lint-staged
      - json-lint
      - bower
      - grunt-cli
      - stylelint
      - get-graphql-schema

- name: Install npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items: "{{ npm_packages }}"

- name: Setup dotfiles
  template:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    force: yes
  with_items:
    - eslintrc
