export PATH="~/bin:$PATH"
export GOPATH="$HOME/.go"
export GO15VENDOREXPERIMENT=1
export SSH_ENV="$HOME/.ssh/environment"
# Set vim as default text editor
export EDITOR=vim
export VISUAL=vim
# Store 5000 commands in history buffer
export HISTSIZE='INFINITY'
# Store 5000 commands in history file
export HISTFILESIZE='ANDBEYOND'
# Avoid duplicates in hisotry
export HISTIGNORE='&:[ ]*'

export GPG_TTY=$(tty)

[ -f ~/.aliases ] && source ~/.aliases
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
# Make sure display get updated when terminal window get resized
shopt -s checkwinsize
# Append to the Bash history file, rather than overwriting it
shopt -s histappend

parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

export PS1="\[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "

function start_agent {
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
     echo succeeded
     chmod 600 "${SSH_ENV}"
     . "${SSH_ENV}" > /dev/null
     /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
     . "${SSH_ENV}" > /dev/null
     #ps ${SSH_AGENT_PID} doesn't work under cywgin
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
         start_agent;
     }
else
     start_agent;
fi
