- name: Add key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
    state: present
  become: true

- name: Add PPA
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present
  become: true

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: true
  changed_when: false

- name: install build depends
  apt:
    name:
      - vim
      - vim-runtime
    state: present
    install_recommends: no
  become: true
