- name: Install gems (linters, checkers, etc)
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
    - mdl
    - haml-lint
    - ruby-lint
    - sqlint
    - rubocop
    - overcommit
