- name: Check OS specifix deps task exists
  local_action: stat path="{{ role_path }}/tasks/deps.{{ os_family }}.yml"
  register: ruby_os_task
  become: no

- name: set shell prefix for system-wide
  set_fact:
    rbenv_shell: ". /etc/profile && "
  when:
    - ansible_os_family == 'Darwin' and rbenv_user_profile

- name: set shell prefix for system-wide
  set_fact:
    rbenv_shell: ". /etc/profile.d/rbenv.sh && "
  when:
    - (ansible_os_family != 'OpenBSD' and ansible_os_family != 'Darwin') and rbenv_user_profile

- name: Include OS specifix ruby task
  include_tasks: "{{ role_path }}/tasks/deps.{{ os_family }}.yml"
  when: ruby_os_task.stat.exists == True

- name: Install ruby
  include_tasks: setup.yml

- name: Install gems (linters, checkers, etc)
  include_tasks: gems.yml
